---
title: "Figure 3"
linestretch: 1.5
fontsize: 10pt
output: 
  bookdown::pdf_document2:
    number_sections: true
    toc: true
    toc_depth: 2
    link-citations: true
---

```{r include = FALSE, echo = FALSE}
library(knitr)
opts_chunk$set(
  fig.path='figure/', 
  self.contained=FALSE,
  dev=c('pdf', 'tiff'),
  dpi = 300,
  cache=FALSE,
  echo = TRUE,
  warning = FALSE,
  message = FALSE,
  fig.align="center"
)
```

# Packages, data and functions

## Packages

```{r echo = TRUE}
library(tidyverse)  
library(here) 
library(survey) 
library(lavaan) 
library(lavaan.survey) 
# lavaan.survey is an extension of lavaan that can deal with data independency. 
# It is no longer on cran, but it is a trustworthy package (there is also a 
# publication for it). The source code is 
# here https://github.com/daob/lavaan.survey. To get the package you need to
# clone the repository linked above and then build the package locally. 
```

## Data
```{r data}
complete.forecasts <- readRDS(here("Data/complete.forecasts.RDS"))

semDD.simplex <- complete.forecasts %>%
  dplyr::filter(forecast.method == "Simplex EDM",
                Target != "Total_biomass",
                Target != "Mean_oxygen") %>%
  ungroup() 
```


# Figure 3

## Models


```{r Fiure3SEM, warning=FALSE, message=FALSE}
model <- 
"
RMSE ~ median_richness + cv.res + pe5 + acf_lag5
cv.res ~ median_richness
pe5 ~ median_richness
acf_lag5 ~ median_richness
cv.res ~~ pe5
"

## create random effect variable
semDD.simplex$group <- paste0(semDD.simplex$Target, "_",
                              semDD.simplex$bottle, "_", 
                              semDD.simplex$incubator)

# semDD.simplex, semDD.rf, semDD.mv, semDD.rnn, semDD.ar
out <- sem(model, data=semDD.simplex, group="light_treatment")

### Survey Design Object
des.card <- svydesign(ids = ~ group, nest=T, data = semDD.simplex)

### Post-Processing
fit.out.survey <- lavaan.survey(out, des.card, estimator = "MLM")

summary(fit.out.survey, standardized=T, rsquare=T)
```


## Figure

Figure 3 was done with MS PowerPoint and the above model.

# Versions of R and of the R-packages used


```{r rdetails, echo = FALSE}
# Base packages:
s <- sessionInfo()
s1 <- s$basePkgs[1]

for (i in 2:length(s$basePkgs)){
  s1 <- paste(s1, ", ", s$basePkgs[i], sep = "")
}

# Other Packages:
pack.info <- installed.packages()
output.packages <- data.frame(pack.info[names(s$otherPkgs),
                                        c("Package","Version")])

s2 <- paste(names(s$otherPkgs)[1],
            output.packages[names(s$otherPkgs)[1], "Version"])

k <- length(names(s$otherPkgs))

if(k>1) {
  for (i in 2:k){
    s2 <- paste(s2, ", ",
                paste(names(s$otherPkgs)[i],
                      output.packages[names(s$otherPkgs)[i], "Version"]),
                sep = "")
  }
}  
```


\textbf{\textsf{R} version}: \textsf{`r s$R.version$version.string`}.

\textbf{Base packages}: \textsf{`r s1`}.

\textbf{Other packages}: \textsf{`r s2`}.

\textbf{This document was generated on `r format(Sys.time(), "%B %d, %Y at %H:%M")`}.